[Logger]
Level = "TRACE"
LogFile="../main.log"
[Storage]
StorageType="sql"

[DB]
DbHost="postgres_db" 
DbPort="5432"
DbName="calend" 
DbUserName="calend" 
DbPassword="calend"

[Http]
Host="127.0.0.103"
Port="5000"

[GRPC]
Host="127.0.0.20"
Port="8080"
