[Logger]
Level="TRACE"
LogFile="../schedule.log"

[DB]
DbHost="postgres_db" 
DbPort="5432"
DbName="calend" 
DbUserName="calend" 
DbPassword="calend"

[Rabbit]
uri="amqp://guest:guest@rabbitmq:5672/"
exchange="calend_shed"
exchangeType="direct"
queue="queue1"
bindingKey="myKey"
SleepSecond=30