[Logger]
Level="TRACE"
LogFile="../sender.log"

[Rabbit]
uri="amqp://guest:guest@rabbitmq:5672/"
exchange="calend_shed"
exchangeType="direct"
queue="queue1"
bindingKey="myKey"
consumerTag="simple-consumer"
SleepSecond=30